#!/bin/bash                                                                                                                                                                                                                                                                                                               #f

for depth in 1 2 4 8 16 32 64 128 256; do
       LD_PRELOAD=./submodules/spdk/build/fio/spdk_nvme ./submodules/fio/fio --ioengine=spdk --thread=1 --filename='trtype=PCIe traddr=0000.88.00.0 ns=2' --zonemode=zbd --zone_append=1 --direct=1  --time_based=1 --ramp_time=5s --runtime=20m --lat_percentiles=1 --write_bw_log=./long/log_zns_${depth}_0 --log_avg_msec=1000 --output-format=json --output=./long/zns_append_${depth}_0.json  --group_reporting=1  --zonemode=zbd  --name=read  --rw=randread --bs=4k --iodepth=${depth} --size=100z --offset=0; sudo ./submodules/spdk/scripts/setup.sh reset; sudo nvme zns finish-zone -a /dev/nvme7n2; sudo PCI_ALLOWED="0000:88:00.0" ./submodules/opt/spdk/scripts/setup.sh;  done;

for depth in 1 2 4 8 16 32 64 128 256; do for rate in 1115 750 250; do
        LD_PRELOAD=./submodules/spdk/build/fio/spdk_nvme ./submodules/fio/fio --ioengine=spdk --thread=1 --filename='trtype=PCIe traddr=0000.88.00.0 ns=2' --zonemode=zbd --zone_append=1 --direct=1  --time_based=1 --ramp_time=5s --runtime=20m --lat_percentiles=1 --write_bw_log=./long/log_zns_${depth}_${rate} --log_avg_msec=1000 --output-format=json --output=./long/zns_append_${depth}_${rate}.json  --name=fill --group_reporting=1  --rw=randwrite --rate=${rate}m,${rate}m --zonemode=zbd --job_max_open_zones=2 --bs=1m --iodepth=32 --offset=100z --size=100z --numjobs=4 --offset_increment=100z  --name=read  --rw=randread --bs=4k --iodepth=${depth} --size=100z --offset=0; sudo ./submodules/spdk/scripts/setup.sh reset; sudo nvme zns finish-zone -a /dev/nvme7n2; sudo PCI_ALLOWED="0000:88:00.0" ./submodules/spdk/scripts/setup.sh;  done; done

for depth in 1 2 4 8 16 32 64 128 256; do
       LD_PRELOAD=./submodules/spdk/build/fio/spdk_nvme ./submodules/fio/fio --ioengine=spdk --thread=1 --filename='trtype=PCIe traddr=0000.af.00.0 ns=1'  --direct=1  --time_based=1 --ramp_time=5s --runtime=20m --lat_percentiles=1 --write_bw_log=./long/log_${depth}_0 --log_avg_msec=1000 --output-format=json --output=./long/nvme_${depth}_0.json  --group_reporting=1  --name=read  --rw=randread --bs=4k --iodepth=${depth} --size=100G --offset=0;  done;

for depth in 1 2 4 8 16 32 64 128 256; do for rate in 1115 750 250; do
        LD_PRELOAD=./submodules/spdk/build/fio/spdk_nvme ./submodules/fio/fio --ioengine=spdk --thread=1 --filename='trtype=PCIe traddr=0000.af.00.0 ns=1' --direct=1  --time_based=1 --ramp_time=5s --runtime=20m --lat_percentiles=1 --write_bw_log=./long/log_${depth}_${rate} --log_avg_msec=1000 --output-format=json --output=./long/nvme_${depth}_${rate}.json  --name=fill --group_reporting=1  --rw=randwrite --rate=${rate}m,${rate}m  --bs=1m --iodepth=32 --offset=100G --size=100G --numjobs=4 --offset_increment=100G  --name=read  --rw=randread --bs=4k --iodepth=${depth} --size=100G --offset=0;  done; done
 
